# What protocol to use when performing Git operations. Supported values: ssh, https.
git_protocol: ssh
# What editor glab should run when creating issues, merge requests, etc. This global config cannot be overridden by hostname.
editor:
# What browser glab should run when opening links. This global config cannot be overridden by hostname.
browser:
# Set your desired Markdown renderer style. Available options are [dark, light, notty]. To set a custom style, refer to https://github.com/charmbracelet/glamour#styles
glamour_style: dark
# Allow glab to automatically check for updates and notify you when there are new updates.
check_update: true
# Whether or not to display hyperlink escape characters when listing items like issues or merge requests. Set to TRUE to display hyperlinks in TTYs only. Force hyperlinks by setting FORCE_HYPERLINKS=1 as an environment variable.
display_hyperlinks: false
# Default GitLab hostname to use.
host: gitlab.com
# Set to true (1) to disable prompts, or false (0) to enable them.
no_prompt: false
# Configuration specific for GitLab instances.
hosts:
    gitlab.com:
        # What protocol to use to access the API endpoint. Supported values: http, https.
        api_protocol: https
        # Configure host for API endpoint. Defaults to the host itself.
        api_host: gitlab.com
        # Your GitLab access token. To get one, read https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html
        token: 84ebaedbaecb4d48de1033f00fa5c606d97e42d0a2abeab1a862e7f3971ef94f
        is_oauth2: "true"
        oauth2_refresh_token: f537d807bcf74a0a0d144fe73f1714764fefb28ece4e0c0008c3ce5d3ef443c7
        oauth2_expiry_date: 15 Jun 24 00:21 WIB
        oauth2_code_verifier: vvUpEMFpBSAxs88KYtpbaqBMfDz9OSPw8XGYVZiI8Pztc
        git_protocol: https
        user: adithyaric
